export const AUTH_ERROR_CODES = {
  CHAIN_NOT_SUPPORTED: "CHAIN_NOT_SUPPORTED",
  WALLET_ADDRESS_INVALID: "WALLET_ADDRESS_INVALID",
  CHAIN_TYPE_UNSUPPORTED: "CHAIN_TYPE_UNSUPPORTED",
  NONCE_INVALID_OR_EXPIRED: "NONCE_INVALID_OR_EXPIRED",
  SIGN_INTENT_MISMATCH: "SIGN_INTENT_MISMATCH",
  NONCE_EXPIRED: "NONCE_EXPIRED",
  SIWE_VERIFY_FAILED: "SIWE_VERIFY_FAILED",
  SOLANA_VERIFY_FAILED: "SOLANA_VERIFY_FAILED",
  SIGNER_ADDRESS_MISMATCH: "SIGNER_ADDRESS_MISMATCH",
  SIGNER_CHAIN_ID_MISMATCH: "SIGNER_CHAIN_ID_MISMATCH",
  SOLANA_NOT_READY: "SOLANA_NOT_READY",
  SOLANA_INVALID_PAYLOAD: "SOLANA_INVALID_PAYLOAD",
  SOLANA_DISABLED: "SOLANA_DISABLED"
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

